### ISSUE TITLE
prepare snap package

### ISSUE THREAD

**Issue by slikef8** [piotr-placzek/hobby-paints-catalog#76]
Create snap package for fast installation and easy update of once installed package

**Comment by piotr-placzek** [comment]
That's a great idea!
I thought about AppImage and some exe file (you have to remember that the target audience is mostly Windows users).
I just wonder when to do it. Right now or later after the gui version is released. Now the application is provided without preconfiguration (a file reserved for patrons).
W chwili obecnej mógłbym do wydań dołączać archiwum z aplikacją przygotowaną do użytku (wraz zależnościami i bazą danych).

**Comment by piotr-placzek** [comment]
That's a great idea!
I thought about AppImage and some exe file (you have to remember that the target audience is mostly Windows users).

I just wonder when to do it. Right now or later after the gui version is released. Now the application is provided without preconfiguration (a file reserved for patrons).

At the moment, I could attach to the releases an archive with the application ready for use (including dependencies and database).

**Comment by piotr-placzek** [comment]
https://snapcraft.io/docs/node-apps

**Comment by piotr-placzek** [comment]
#82
